#Top Makefile for C program

all:
	$(MAKE) -C ./testA
	$(MAKE) -C ./testB
	$(MAKE) -C ./main

clean:
	$(MAKE) -C ./testA clean
	$(MAKE) -C ./testB clean
	$(MAKE) -C ./main clean
	$(RM)	libs/*

	































	
